moniker: "nyc_open_data_311_customer_satisfaction_survey"
schema:
  - year
  - campaign
  - channel
  - survey_type
  - start_time
  - completion_time
  - survey_language
  - overall_satisfaction
  - wait_time
  - agent_customer_service
  - agent_job_knowledge
  - answer_satisfaction
  - nps
fetcher: FetcherNYCOpenData
token: ERZjPaQcb5J6iJOZeF1BDu4hd
base_url: data.cityofnewyork.us
url: "kizp-4dfk"
