moniker: "nyc_open_data_311_service_requests"
schema:
  - address_type
  - agency
  - agency_name
  - borough
  - bridge_highway_direction
  - bridge_highway_name
  - bridge_highway_segment
  - city
  - closed_date
  - community_board
  - complaint_type
  - created_date
  - cross_street_1
  - cross_street_2
  - descriptor
  - due_date
  - facility_type
  - ferry_direction
  - ferry_terminal_name
  - garage_lot_name
  - incident_address
  - incident_zip
  - intersection_street_1
  - intersection_street_2
  - landmark
  - latitude
  - location
  - location_type
  - longitude
  - park_borough
  - park_facility_name
  - resolution_action_updated_date
  - road_ramp
  - school_address
  - school_city
  - school_code
  - school_name
  - school_not_found
  - school_number
  - school_or_citywide_complaint
  - school_phone_number
  - school_region
  - school_state
  - school_zip
  - status
  - street_name
  - taxi_company_borough
  - taxi_pick_up_location
  - unique_key
  - vehicle_type
  - x_coordinate_state_plane_
  - y_coordinate_state_plane_
fetcher: FetcherNYCOpenData
validator: ValidatorNYCOpen311Service
token: ERZjPaQcb5J6iJOZeF1BDu4hd
base_url: data.cityofnewyork.us
url: "3rfa-3xsf"
