moniker: "nyc_open_data_311_call_center_inquiry"
schema:
  - unique_id
  - date
  - time
  - date_time
  - agency
  - agency_name
  - inquiry_name
  - brief_description
  - call_resolution
fetcher: FetcherNYCOpenData
token: ERZjPaQcb5J6iJOZeF1BDu4hd
base_url: data.cityofnewyork.us
url: "wewp-mm3p"
